[package]
name = "ubotdw"
version = "0.1.0"
edition = "2024"

[lib]
name = "ubotdw"
crate-type = ["staticlib", "lib"]

[dependencies]
wgpu = "30.0.1"
futures = "0.3"
raw-window-handle = "0.6.2"
objc2 = "0.6.4"
objc2-ui-kit = "0.3.2"
bytemuck = "1.25.2"
thiserror = "2.0.20"

[build-dependencies]
cbindgen = "0.29"
